# Custom Language File for Launcher Customizer

[ejs.app]
title = "우캣월드"

[ejs.landing]
mediaGitHubURL = "https://github.com/sinjkd351/woocatworld"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/wtvUwWwqwh"

[ejs.settings]
sourceGithubLink = "https://github.com/sinjkd351/woocatworld"
supportLink = "https://github.com/sinjkd351/woocatworld/issues"

[ejs.welcome]
welcomeHeader = "우캣월드에 오신 것을 환영합니다"
welcomeDescription = "해당 런처는 '아이곰(discord: babybear7)'에 의해 제작되었습니다."
welcomeDescCTA = "몇번만 더 클릭하시면 됩니다!"
